name: erp_flutter
description: ERP Flutter client
publish_to: 'none'
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.24.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.0
  cookie_jar: ^4.0.8
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  webview_flutter: ^4.10.0
  android_intent_plus: ^5.2.0
  font_awesome_flutter: ^10.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
flutter:
  uses-material-design: true
  assets:
    - android/app/src/logo.png

flutter_icons:
  android: true
  ios: false
  image_path: android/app/src/logo.png
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: android/app/src/logo.png
  android: true
  ios: false
